## Numpy_test - Amjad Ali

__Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)__

In [ ]:
import numpy as np
matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
matrix

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

__Given a 1D array, negate all elements which are between 3 and 8, in place__

In [ ]:
array = np.arange(10)
n_array = np.negative(array[4:8])
print(array)
print(n_array)

[0 1 2 3 4 5 6 7 8 9]
[-4 -5 -6 -7]


__What are the result of the following expressions?__

#np.array(0) // np.array(0)
#np.array(0) // np.array(0.) 
#np.array(0) / np.array(0) 
#np.array(0) / np.array(0.)

In [ ]:
print("These all result in either warning or 'NaN' i.e Not a number. This happens because the answer undefined")

These all result in either warning or 'NaN' i.e Not a number. This happens because the answer undefined


__Create a 2d array with 1 on the border and 0 inside__

In [ ]:
twoD = np.ones((10,10))
twoD[1:-1,1:-1]=0
twoD

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

__Create a random array of size 30 and find the mean value__

In [ ]:
array = np.random.random(10)
print(array.mean())

0.47725510444495073


__Create a 10x10 array with random values and find the minimum and maximum values__

In [ ]:
m = np.random.random((10,10))
print("Minimum value:",m.min())
print("Maximum value:",m.max())

Minimum value: 0.009066752816749624
Maximum value: 0.9957635628381133


__Create a 3x3x3 array with random values__

In [ ]:
print(np.random.uniform((3,3,3)))

[1.39552239 2.22620446 1.17142293]


__Create a 3x3 identity matrix___

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


__Find indices of non­zero elements from [1,2,0,0,4,0]__

In [ ]:
A = [1,2,0,0,4,0]
np.nonzero(A)

(array([0, 1, 4]),)

__Reverse a Array__

In [ ]:
Array = np.arange(10)
print(Array[::-1])

[9 8 7 6 5 4 3 2 1 0]


__Create a null array of size 10 but the fifth value which is 1__

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

__How to get the documentation of the numpy add function from the command line?__

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

__Print the numpy version and the configuration__

In [ ]:
print("Numpy version:",np.__version__)
print()
print()
print("\n\nNumpy configuration:",np.show_config())

Numpy version: 1.18.5


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


Numpy configuration: None


__Create a vector of size 10 with values ranging from 0 to 1, both excluded__

In [ ]:
print(np.linspace(0,1,12,endpoint=True)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


__Consider two random array A and B, check if they are equal__

In [ ]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(np.equal(A,B))

[False False False False False False False  True False False]
